target/codeql-java-maven-index-reader-0.0.1-SNAPSHOT.jar target/lib/lucene-codecs-4.10.2.jar target/lib/lucene-core-4.10.2.jar: pom.xml src/main/java/com/github/codeql/maven/index/reader/Main.java
	mvn package
